spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b9884425b2394c26042d
            client-secret: 29931021df543971f6b779cbb56cb55c013f2d9e
  datasource:
    url: jdbc:mysql://localhost:3307/roadmap_project
    username: group37
    password: password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: eductrackteam@gmail.com
    password: hhlj qqmu ikzu okpa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  springframework:
    jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE
    security: DEBUG
